# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e1033dc2b028fca58f395b8d6ac51fec9bc9f0360d67471da780dc0dde897c1cec1fc8fba507e1b61a6088581c4b5882974cb313487c801f7651ee9d39f3ca7

test:
  secret_key_base: a6860430dc8af946ab83381a6598b41b0acf377a38c6623988308ced98d7ed0e68fe9c210247b1949aa2663beea1eeca8d9c37d13bbb06b9a2e5afb7528f2cb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
